### AGROLINK API TESTS
# You can run these tests using the "REST Client" extension in VS Code.
# Just click the "Send Request" button above any of the requests below.

@baseUrl = http://localhost:8080/api

### 1. Sign up a Farmer
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "password": "password123",
    "role": "FARMER",
    "firstName": "Kamal",
    "lastName": "Perera",
    "phoneNumber": "0771234567",
    "nic": "901234567V",
    "farmerPhotoUrl": "https://example.com/farmer.jpg",
    "gnCertificateUrl": "https://example.com/gs-certificate.pdf"
}


### 2. Sign up an Investor
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "password": "investorpass",
    "role": "INVESTOR",
    "firstName": "Nimal",
    "lastName": "Silva",
    "phoneNumber": "0715550000",
    "nic": "200012345678"
}


### 3. Login as Farmer (Copy the 'userId' from the response!)
# @name farmerLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "phoneNumber": "0771234567",
    "password": "password123",
    "role": "FARMER"
}


### 4. Login as Investor (Copy the 'userId' from the response!)
# @name investorLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "phoneNumber": "0715550000",
    "password": "investorpass",
    "role": "INVESTOR"
}


### 5. Create a Farmer Project (PENDING_REVIEW by default)
# Replace FARMER_ID_HERE with the farmerLogin response userId.
POST {{baseUrl}}/farmer-project/create
Content-Type: application/json

{
    "farmerId": "FARMER_ID_HERE",
    "projectTitle": "Maha Season Paddy - 2026",
    "cropType": "Paddy",
    "location": "Anuradhapura",
    "fundingGoal": 250000,
    "minimumInvestment": 5000,
    "durationInMonths": 4,
    "minRoi": 12,
    "maxRoi": 18,
    "description": "Seasonal paddy cultivation project.",
    "photos": ["https://example.com/field_image.jpg"]
}


### 6. Farmer Dashboard aggregate (totalRaisedLkr, alerts, active projects)
GET {{baseUrl}}/farmer/dashboard/FARMER_ID_HERE


### 7. Investor: view all projects
GET {{baseUrl}}/farmer-project/all


### 8. Investor: invest in a project
# Replace PROJECT_ID_HERE and INVESTOR_ID_HERE with real IDs.
POST {{baseUrl}}/investments/invest
Content-Type: application/json

{
    "projectId": "PROJECT_ID_HERE",
    "investorId": "INVESTOR_ID_HERE",
    "amount": 50000
}


### 9. Farmer: manage updates (post + fetch timeline)
POST {{baseUrl}}/updates/post
Content-Type: application/json

{
    "projectId": "PROJECT_ID_HERE",
    "farmerId": "FARMER_ID_HERE",
    "content": "Harvest started",
    "mediaUrls": ["https://example.com/harvest.jpg"]
}

### 10. Farmer: fetch all updates for management (pending + verified)
GET {{baseUrl}}/updates/project/PROJECT_ID_HERE/manage?farmerId=FARMER_ID_HERE

### 11. Shared: link bank account + withdraw simulation
POST {{baseUrl}}/profile/payment/link-bank-account
Content-Type: application/json

{
    "userId": "FARMER_ID_HERE",
    "bankName": "Bank of Ceylon",
    "accountNumber": "1234567890"
}

POST {{baseUrl}}/profile/payment/withdraw
Content-Type: application/json

{
    "userId": "FARMER_ID_HERE",
    "amount": 25000
}


### 8. Invest in a Project
# Replace the IDs below!
POST {{baseUrl}}/investments/invest
Content-Type: application/json

{
    "projectId": "PROJECT_ID_HERE",
    "investorId": "INVESTOR_ID_HERE",
    "amount": 50000
}
