# -*- coding: utf-8 -*-
"""AgroLink_AI_Day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uX1xLQxM6kmnjNZadoiga0XaR-aOBAmq
"""

import pandas as pd
import numpy as np

df = pd.read_csv('crop_production.csv')  # if uploaded directly
df.head()

df.info()
df.describe()

df = df.dropna(subset=['Production'])

df['Crop'] = df['Crop'].str.lower().str.strip()
df['Season'] = df['Season'].str.lower().str.strip()
df['District_Name'] = df['District_Name'].str.lower().str.strip()

threshold = df['Production'].median()
threshold

df['success_label'] = np.where(
    df['Production'] >= threshold, 1, 0
)

df['success_label'].value_counts()

final_df = df[
    ['Crop', 'Season', 'District_Name', 'Area', 'Production', 'success_label']
]

final_df.head()

final_df.to_csv('agrolink_core_dataset.csv', index=False)