# -*- coding: utf-8 -*-
"""AgroLink_AI_Day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uX1xLQxM6kmnjNZadoiga0XaR-aOBAmq
"""

import pandas as pd

df = pd.read_csv('crop_production.csv')

df[['Crop', 'Production']].head()

df['success_label'] = df.groupby('Crop')['Production'].transform(
    lambda x: (x >= x.median()).astype(int)
)

df['success_label'].value_counts()
df[df['Crop'] == df['Crop'].iloc[0]][['Crop', 'Production', 'success_label']].head()

final_df = df[
    ['Crop', 'Season', 'District_Name', 'Area', 'Production', 'success_label']
]

final_df = final_df.rename(columns={
    'Crop': 'crop_type',
    'Season': 'season',
    'District_Name': 'region',
    'Area': 'area_hectare',
    'Production': 'production'
})

final_df.to_csv('agrolink_core_dataset.csv', index=False)